name: thirdfactor
description: "Flutter package for ThirdFactor Verification"
version: 0.0.4
publish_to: none

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 
    git:
      url: https://github.com/khalti/flutter-permission-handler.git
      path: permission_handler
      ref: main
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.14.0
  webview_flutter_wkwebview: ^3.10.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.1.8
  webview_flutter_platform_interface: ^2.10.0
